-- David 戰情室 V13 Cloud
-- 請在 Supabase > SQL Editor 執行一次

create table if not exists public.stock_history (
    id bigint generated by default as identity primary key,
    trade_date date not null,
    code text not null,
    name text not null,
    market text not null check (market in ('TW','TWO')),
    symbol text not null,
    prev_close numeric,
    open_price numeric,
    close_price numeric,
    change_value numeric,
    change_pct numeric,
    volume_ratio numeric,
    bias_pct numeric,
    morning text,
    momentum text,
    cost text,
    strength text,
    buy_score integer,
    sell_score integer,
    fib_position text,
    decision text,
    updated_at timestamptz not null default now(),
    constraint stock_history_trade_code_unique unique (trade_date, code)
);

create index if not exists idx_stock_history_code_date
    on public.stock_history (code, trade_date desc);

create table if not exists public.stock_config (
    position integer primary key check (position between 1 and 100),
    code text not null unique,
    name text not null,
    market text not null check (market in ('TW','TWO')),
    updated_at timestamptz not null default now()
);

-- V13 使用 Streamlit Secrets / GitHub Secrets 中的 Supabase Secret/Service Role Key。
-- 請勿把 Secret/Service Role Key 寫進 GitHub 公開程式碼。
